[package]
name = "fastq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.3.0"
clap = { version = "4.3.8", features = ["derive"] }
serde = "1.0.164"
serde_json = "1.0.99"
